import { Obligation, Category } from '@/types/finance';

// Demo obligations data based on user's context
export const demoObligations: Obligation[] = [
  // HOUSING - Uncompromised
  {
    id: '1',
    name: 'Whitfield Levies',
    provider: 'Whitfield Body Corporate',
    category: 'HOUSING',
    amount: 3506.39,
    debitOrderDate: 27,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Home Loan',
    provider: 'Nedbank',
    category: 'HOUSING',
    amount: 12500,
    totalBalance: 1250000,
    interestRate: 11.75,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Rates & Taxes',
    provider: 'City of Johannesburg',
    category: 'HOUSING',
    amount: 900,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // UTILITIES - Uncompromised
  {
    id: '4',
    name: 'Electricity',
    provider: 'City Power',
    category: 'UTILITIES',
    amount: 1200,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Fibre Internet',
    provider: 'Vumatel',
    category: 'UTILITIES',
    amount: 899,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // DEBT
  {
    id: '6',
    name: 'Credit Card',
    provider: 'Nedbank',
    category: 'DEBT',
    amount: 2500,
    totalBalance: 45000,
    interestRate: 21.5,
    debitOrderDate: 15,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Personal Loan',
    provider: 'FNB',
    category: 'DEBT',
    amount: 3200,
    totalBalance: 78000,
    interestRate: 18.0,
    debitOrderDate: 25,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // INSURANCE
  {
    id: '8',
    name: 'Car Insurance',
    provider: 'OUTsurance',
    category: 'INSURANCE',
    amount: 1450,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: 'Life Cover',
    provider: 'Liberty',
    category: 'INSURANCE',
    amount: 850,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // LIVING - Variable
  {
    id: '10',
    name: 'Daycare',
    provider: 'Little Stars Academy',
    category: 'LIVING',
    amount: 3500,
    debitOrderDate: 1,
    isUncompromised: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: 'Groceries (est.)',
    provider: 'Various',
    category: 'GROCERIES',
    amount: 4500,
    debitOrderDate: 15,
    isUncompromised: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // TRANSPORT
  {
    id: '12',
    name: 'Fuel (est.)',
    provider: 'Various',
    category: 'TRANSPORT',
    amount: 2000,
    debitOrderDate: 15,
    isUncompromised: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  // SAVINGS
  {
    id: '13',
    name: 'Emergency Fund',
    provider: 'TFSA',
    category: 'SAVINGS',
    amount: 2000,
    debitOrderDate: 25,
    isUncompromised: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Demo settings
export const demoSettings = {
  monthlyIncome: 55000,
  payday: 25,
  currency: 'ZAR',
};
